export default [
    {
        id: "1",
        branch: 'CSE',
        semester: "1",
        subject: 'Maths',
        unit: "1",
        submittedBy: 'Rahul Kumar',
        approvedBy: 'Rajesh Kumar',
        date: '2019-01-01',
        likes: "10",
        dislikes: "2",
        views: "100",
        downloads: "50",
    },
    {
        id: "2",
        branch: 'ECE',
        semester: "2",
        subject: 'Physics',
        unit: "2",
        submittedBy: 'Bhavesh Kumar',
        approvedBy: 'Kamal Kumar',
        date: '2019-02-01',
        likes: "22",
        dislikes: "12",
        views: "200",
        downloads: "100",
    },
    {
        id: "3",
        branch: 'EEE',
        semester: "3",
        subject: 'Chemistry',
        unit: "3",
        submittedBy: 'Rahul Kumar',
        approvedBy: 'Rajesh Kumar',
        date: '2019-03-01',
        likes: "102",
        dislikes: "25",
        views: "100",
        downloads: "50",
    },
    {
        id: "4",
        branch: 'CSE',
        semester: "4",
        subject: 'Maths',
        unit: "4",
        submittedBy: 'Rahul Kumar',
        approvedBy: 'Rajesh Kumar',
        date: '2019-04-01',
        likes: "10",
        dislikes: "2",
        views: "100",
        downloads: "50",
    },
    {
        id: "5",
        branch: 'Mech',
        semester: "5",
        subject: 'Physics',
        unit: "5",
        submittedBy: 'Bhavesh Kumar',
        approvedBy: 'Kamal Kumar',
        date: '2019-05-01',
        likes: "22",
        dislikes: "12",
        views: "200",
        downloads: "100",
    },
    {
        id: "6",
        branch: 'CIVIL',
        semester: "6",
        subject: 'Hindi',
        unit: "5",
        submittedBy: 'Rahul Kumar',
        approvedBy: 'Rajesh Kumar',
        date: '2019-06-01',
        likes: "102",
        dislikes: "25",
        views: "100",
        downloads: '50',
    },
]